Beyza  GOK API Week1
HackYourHomework/Homework-class38 pull request #43
Opened 2022-07-04 10:52 UTC by beyzagoknl

2022-07-07 16:16 UTC, ObadaElSharbatly requested changes
Good work Beyza I think you just need to modify a small thing. but it seems that you did understand the idea of Promises so that's great job 💥💥

2022-07-07 16:16 UTC, ObadaElSharbatly commented on 3-UsingAPIs/Week1/homework/ex3-rollDie.js
>  function main() {
I think you forgot to refactor this `main` function to deal with the promise coming from the `rollDie` function.
you need to modify this 😀

2022-07-07 16:16 UTC, ObadaElSharbatly commented on 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js
> +  return Promise.all(dice.map(rollDie));
prefect

2022-07-07 16:16 UTC, ObadaElSharbatly commented on 3-UsingAPIs/Week1/homework/ex5-pokerDiceChain.js
> +    })
greate

2022-07-08 08:32 UTC, ObadaElSharbatly approved these changes

2022-07-08 14:27 UTC, beyzagoknl commented
> Good work Beyza I think you just need to modify a small thing. but it seems that you did understand the idea of Promises so that's great job 💥💥

Thank you for your time and your comments.

2022-09-06 18:05 UTC, closed without merging